name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: MVCVueResourceGroup
  LOCATION: southeastasia
  ACR_NAME: jadebiregistry
  APP_SERVICE_PLAN: jadebi
  WEB_APP_NAME: jadebishop
  IMAGE_NAME: my-jadebi-app
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Login Azure bằng Service Principal
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Bước 5: Gán quyền Contributor cho App Service Principal
    - name: Assign Contributor role to Service Principal
      run: |
        SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        SP_ID=$(az ad signed-in-user show --query id -o tsv)
        az role assignment create --assignee $SP_ID --role "Contributor" --scope /subscriptions/$SUBSCRIPTION_ID

    # Bước 6: Đăng nhập vào ACR
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Bước 7: Build và push image
    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Bước 8: Tạo App Service Plan + Web App nếu chưa có
    - name: Create App Service Plan and Web App
      run: |
        az appservice plan show --name ${{ env.APP_SERVICE_PLAN }} --resource-group ${{ env.RESOURCE_GROUP }} || \
        az appservice plan create --name ${{ env.APP_SERVICE_PLAN }} --resource-group ${{ env.RESOURCE_GROUP }} --is-linux --sku B1
        az webapp show --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} || \
        az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.APP_SERVICE_PLAN }} --name ${{ env.WEB_APP_NAME }} --deployment-container-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Bước 9: Cấu hình App Service dùng image mới nhất
    - name: Configure Web App to use container image
      run: |
        az webapp config container set \
          --name ${{ env.WEB_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
