name: Build, Push, and Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: MVCVueResourceGroup
  ACR_NAME: jadebiregistry
  WEBAPP_NAME: jadebishop
  IMAGE_NAME: my-jadebi-app

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Login Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Bước 3: Build & Push image lên ACR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Bước 4: Cấp quyền AcrPull cho Web App (nếu chưa có)
      - name: Assign AcrPull role to Web App
        run: |
          WEBAPP_ID=$(az webapp show --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP --query identity.principalId -o tsv)
          ACR_ID=$(az acr show --name $ACR_NAME --query id -o tsv)
          az role assignment create --assignee $WEBAPP_ID --role AcrPull --scope $ACR_ID || echo "Role already exists"

      # Bước 5: Cập nhật Web App chạy image mới
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_NAME.azurecr.io/${IMAGE_NAME}:latest \
            --docker-registry-server-url https://$ACR_NAME.azurecr.io
