name: Build and Deploy to Azure Web App (Container)
on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: MVCVueResourceGroup
  LOCATION: southeastasia
  ACR_NAME: jadebiregistry
  APP_SERVICE_PLAN: jadebi
  WEB_APP_NAME: jadebishop
  IMAGE_NAME: my-jadebi-app
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login Azure bằng Service Principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Gán role Contributor cho Service Principal (nếu chưa có)
      - name: Ensure SP has Contributor role
        run: |
          SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          SP_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')
          echo "Granting Contributor role to $SP_ID..."
          az role assignment create --assignee $SP_ID --role "Contributor" --scope /subscriptions/$SUBSCRIPTION_ID || echo "Already assigned"

      # 4️⃣ Đăng nhập vào ACR
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 5️⃣ Build & Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 6️⃣ Đảm bảo Managed Identity của WebApp có quyền AcrPull (tự động gán)
      - name: Grant WebApp Managed Identity AcrPull
        run: |
          WEBAPP_ID=$(az webapp show --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query identity.principalId -o tsv)
          ACR_ID=$(az acr show --name ${{ env.ACR_NAME }} --query id -o tsv)
          echo "Granting AcrPull to WebApp identity..."
          az role assignment create --assignee $WEBAPP_ID --role AcrPull --scope $ACR_ID || echo "Already has AcrPull"

      # 7️⃣ Deploy container image mới lên Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
